application: matsumoto26sunday
version: 2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stats
  script: stats.py
- url: /createEleven
  script: create_eleven.py
- url: /spread
  script: spread.py
- url: /pool
  script: pool.py
- url: /scoreboard
  script: scoreboard.py
- url: /templates
  script: templates.py
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico